### ISSUE TITLE
Expand token model

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/devzact#107]
## Tasks

* [x] Add `type` field to Token model
* [x] Add `data` field to Token model
* [x] Refactor verification functionality

## Token model

New token model explained

* `owner` - ID reference of user who owns the token
* `type` - type of token this object represents
* `value` - the actual token (string)
* `data` - any data associated with the token (e.g. new email)
* `createdAt` - when the token was created
