### ISSUE TITLE
Change placement of edit and delete project

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/devzact#97]
## Tasks

* [x] Change project edit button icon to gear
* [x] Change project edit button text to Settings
* [x] Remove project delete button
* [x] Add project delete button to edit project modal

## Reference screenshot

![image](https://user-images.githubusercontent.com/14854181/94668817-d0a89000-0310-11eb-9392-4087a0b6b02a.png)
